# Generated by Django 3.1.6 on 2021-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='test',
            field=models.CharField(default=1, max_length=32, verbose_name='태그test'),
            preserve_default=False,
        ),
    ]
