# Generated by Django 3.1.6 on 2021-02-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='test',
        ),
    ]
