# Generated by Django 3.1.7 on 2021-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.TextField(verbose_name='재고'),
        ),
    ]
