# Generated by Django 3.1.7 on 2021-03-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210305_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
